<php

/**
* Implements hook_install().
*/
function dcycle_deploy_install() {
  for ($i = 7001; $i < 8000; $i++) {
    $candidate = 'dcycle_deploy_update_' . $i;
    if (function_exists($candidate)) {
      $candidate();
    }
  }
}
/**
 * #12347: New theme for the site
 */
function resto_deploy_update_7003() {
  theme_enable(array('nhahang_theme'));
  variable_set('theme_default', 'nhahang_theme');
}
function resto_deploy_update_7004() {
  variable_set('commerce_default_currency', 'EUR');
}
